# -*- coding: utf-8 -*-
"""mass mail

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1C9q-BfsEfwJrkn1CoLvHb_su3-CKR2U3
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
import smtplib

SenderAddress = "Likithae.ic.19@nitj.ac.in"
password = "972510535584"

e = pd.read_csv("BULKEMAIL.csv")
emails = e['Email Address'].values
server = smtplib.SMTP("smtp.gmail.com", 587)
server.starttls()
server.login(SenderAddress, password)
msg = "Hello this is a email form python"
subject = "Hello world"
body = "Subject: {}\n\n{}".format(subject,msg)
for email in emails:
    server.sendmail(SenderAddress, email, body)
server.quit()



